### ISSUE TITLE
Accessories No Response on Homekit

### ISSUE THREAD

**Issue by derk1127** [fjs21/homebridge-kumo#11] opened 2020-10-21 06:31 UTC
Hello I installed and it found all of my headhunts. However when I open up Homekit it shows that my head units are "No Response" on the alerts. I can still control the head units even if thy indicate "No Response" on my headunits. I suspect that the wifi adapters may be going into a standby mode. Does anyone else have this issue? Thanks

**Comment by fjs21** [comment] 2020-10-24 14:22
I have noticed this occurring since the iOS 14 update. Everything seems to work fine but I get the 'No response' in the upper panel, maybe in relation to the temperature? I will need to troubleshoot further to find out what causes this.

**Comment by derk1127** [comment] 2020-10-26 03:04
I’ve noticed everything worked fine as well and the “No Response” is in gray versus red when there really is a device with no response.

**Comment by derk1127** [comment] 2020-11-21 03:42
Has anyone else had this bug come up?

**Comment by fjs21** [comment] 2020-11-21 05:49
Ok. I think I fixed it in the latest beta version. Please try the latest beta.

> sudo npm install -g homebridge-kumo@beta

Please note this version also combines the fan control (speed and swing mode) into the heater/cooler. You will need to remove the cached accessory to remove the fan and power switch which are now redundant.

Finally, this version is starting to add support for the older v1 WiFi modules. It's a beta because I'm not 100% sure it will have some unwanted effects with existing support. It works for me but I want to be careful in case it breaks other peoples setups. Let me know.

**Comment by derk1127** [comment] 2020-11-21 07:16
I still get the no response issue on some of my units when I open up the home app. When it says no response, I can’t control the fan speed on that unit from HomeKit. When I turn on the fan in the kumo app, the no response goes away. But if I start the HomeKit app again after closing kumo and HomeKit, some of my units come up as no response. I tried connecting locally and through the cloud and both have the same issue. Also is there a way to disable the auto setting on the tenperature setting? Thanks!!

**Comment by derk1127** [comment] 2020-11-22 06:29
I just noticed that even if HomeKit indicates the unit is on, if that unit is listed as non responsive, I cannot change its fan speed. I should note my system has two zones because I have two heat exchangers, one for each floor.

**Comment by fjs21** [comment] 2020-11-22 12:46
To help debug the issue, can you turn on debugging in Homebridge? It is available in the Homebridge settings page of the UI. 

Please could you post some of the response you receive from the unit (and the initial response when Homebridge starts and the accessory is initialized).

**Comment by derk1127** [comment] 2020-11-22 17:49
I tried logging right as everything started up. It went from 6 no response to 3 no response. I hope this is the right log. I don't know a whole lot about pi.

[11/22/2020, 9:47:30 AM] [Kumo] queryDevice success.
[11/22/2020, 9:47:30 AM] [Kumo] Kumo response: [
  true,
  null,
  [
    [
      {
        active_thermistor: null,
        actual_fan_speed: null,
        air_direction: 0,
        device_serial: '9534P008F100132F',
        fan_speed: 0,
        id: '2252139211126380',
        it_status: null,
        operation_mode: 16,
        out_of_use: null,
        power: 0,
        prohibit_local_remote_control: null,
        raw_frames: null,
        record_time: '2020-11-22T17:47:06.012Z',
        room_temp: 21,
        room_temp_a: null,
        room_temp_beyond: null,
        rssi: -59,
        run_test: 0,
        seconds_since_contact: 25,
        set_temp: null,
        set_temp_a: null,
        sp_auto: -1,
        sp_cool: 24,
        sp_heat: 21,
        status_display: 0,
        temp_source: null,
        two_figures_code: 'A0',
        unusual_figures: 32768
      }
    ],
    []
  ]
]
[11/22/2020, 9:47:30 AM] [Kumo] queryDevice success.
[11/22/2020, 9:47:30 AM] [Kumo] Kumo response: [
  true,
  null,
  [
    [
      {
        active_thermistor: null,
        actual_fan_speed: null,
        air_direction: 0,
        device_serial: '9834P008P100247F',
        fan_speed: 6,
        id: '2253470672600840',
        it_status: null,
        operation_mode: 1,
        out_of_use: null,
        power: 1,
        prohibit_local_remote_control: null,
        raw_frames: null,
        record_time: '2020-11-22T17:47:04.261Z',
        room_temp: 20.5,
        room_temp_a: null,
        room_temp_beyond: null,
        rssi: -42,
        run_test: 0,
        seconds_since_contact: 27,
        set_temp: null,
        set_temp_a: null,
        sp_auto: -1,
        sp_cool: 24.5,
        sp_heat: 21.5,
        status_display: 0,
        temp_source: null,
        two_figures_code: 'A0',
        unusual_figures: 32768
      }
    ],
    []
  ]
]
[11/22/2020, 9:47:30 AM] [Kumo] queryDevice success.
[11/22/2020, 9:47:30 AM] [Kumo] Kumo response: [
  true,
  null,
  [
    [
      {
        active_thermistor: null,
        actual_fan_speed: null,
        air_direction: 0,
        device_serial: '9834P008E100060F',
        fan_speed: 0,
        id: '2252517203731217',
        it_status: null,
        operation_mode: 16,
        out_of_use: null,
        power: 0,
        prohibit_local_remote_control: null,
        raw_frames: null,
        record_time: '2020-11-22T17:47:13.637Z',
        room_temp: 22,
        room_temp_a: null,
        room_temp_beyond: null,
        rssi: -43,
        run_test: 0,
        seconds_since_contact: 17,
        set_temp: null,
        set_temp_a: null,
        sp_auto: -1,
        sp_cool: 25,
        sp_heat: 22,
        status_display: 0,
        temp_source: null,
        two_figures_code: 'A0',
        unusual_figures: 32768
      }
    ],
    []
  ]
]
[11/22/2020, 9:47:30 AM] [Kumo] queryDevice success.
[11/22/2020, 9:47:30 AM] [Kumo] Kumo response: [
  true,
  null,
  [
    [
      {
        active_thermistor: null,
        actual_fan_speed: null,
        air_direction: 0,
        device_serial: '9534P008F100132F',
        fan_speed: 0,
        id: '2252139211126380',
        it_status: null,
        operation_mode: 16,
        out_of_use: null,
        power: 0,
        prohibit_local_remote_control: null,
        raw_frames: null,
        record_time: '2020-11-22T17:47:06.012Z',
        room_temp: 21,
        room_temp_a: null,
        room_temp_beyond: null,
        rssi: -59,
        run_test: 0,
        seconds_since_contact: 25,
        set_temp: null,
        set_temp_a: null,
        sp_auto: -1,
        sp_cool: 24,
        sp_heat: 21,
        status_display: 0,
        temp_source: null,
        two_figures_code: 'A0',
        unusual_figures: 32768
      }
    ],
    []
  ]
]
[11/22/2020, 9:47:30 AM] [Kumo] queryDevice success.
[11/22/2020, 9:47:30 AM] [Kumo] Kumo response: [
  true,
  null,
  [
    [
      {
        active_thermistor: null,
        actual_fan_speed: null,
        air_direction: 0,
        device_serial: '9534P008F100132F',
        fan_speed: 0,
        id: '2252139211126380',
        it_status: null,
        operation_mode: 16,
        out_of_use: null,
        power: 0,
        prohibit_local_remote_control: null,
        raw_frames: null,
        record_time: '2020-11-22T17:47:06.012Z',
        room_temp: 21,
        room_temp_a: null,
        room_temp_beyond: null,
        rssi: -59,
        run_test: 0,
        seconds_since_contact: 25,
        set_temp: null,
        set_temp_a: null,
        sp_auto: -1,
        sp_cool: 24,
        sp_heat: 21,
        status_display: 0,
        temp_source: null,
        two_figures_code: 'A0',
        unusual_figures: 32768
      }
    ],
    []
  ]
]
[11/22/2020, 9:47:30 AM] [Kumo] queryDevice success.
[11/22/2020, 9:47:30 AM] [Kumo] Kumo response: [
  true,
  null,
  [
    [
      {
        active_thermistor: null,
        actual_fan_speed: null,
        air_direction: 0,
        device_serial: '9834P008E100019F',
        fan_speed: 0,
        id: '2252650324737898',
        it_status: null,
        operation_mode: 16,
        out_of_use: null,
        power: 0,
        prohibit_local_remote_control: null,
        raw_frames: null,
        record_time: '2020-11-22T17:46:58.797Z',
        room_temp: 21,
        room_temp_a: null,
        room_temp_beyond: null,
        rssi: -59,
        run_test: 0,
        seconds_since_contact: 32,
        set_temp: null,
        set_temp_a: null,
        sp_auto: -1,
        sp_cool: 25,
        sp_heat: 21,
        status_display: 0,
        temp_source: null,
        two_figures_code: 'A0',
        unusual_figures: 32768
      }
    ],
    []
  ]
]
[11/22/2020, 9:47:30 AM] [Kumo] queryDevice success.

**Comment by fjs21** [comment] 2020-12-10 20:48
Sorry for the delayed reply. 2020 happened. I'm not seeing an error in your log. It looks good - I see successful responses from four separate devices. Can you confirm which version of homebridge-kumo you are running?

You can find on the homebridge-ui-x under the Plugin tab. See below. I'm running the latest beta:
![image](https://user-images.githubusercontent.com/65719819/101827903-e00d3c00-3afe-11eb-8be9-ba0c916e5dae.png)

**Comment by derk1127** [comment] 2020-12-10 21:27
I am running 1.2.11-beta.0. It still shows three accessories no response. Do you think it is because I have two zones set up? I have 6 head units in total in two zones. The no response error makes it so I cannot set fan speed on the units that are listed as no response.

**Comment by fjs21** [comment] 2020-12-11 19:28
I think it would be a good idea to match up each of your units to their serial numbers. That way you can track their responses in the log and see if you can identify what might be different for the three units which are giving you issues and the three that appear to be working correctly. The log above details four units. 

> 9534P008F100132F - off
> 9834P008P100247F - on - heating to 21.5 deg C with fan set on 6 
> 9834P008E100060F - off
> 9834P008E100019F - off

I think they all appear 'ok'. Unfortunately, its very hard to diagnose what's going wrong. What does the log look like immediately after you issue a change to the fan on one of the problem units?

**Comment by derk1127** [comment] 2020-12-11 22:19
Here is what happens after i try to turn on the "non responsive" head units.

}
[12/11/2020, 2:15:09 PM] [Kumo] queryDevice_Direct success.
[12/11/2020, 2:15:09 PM] [Kumo] post_data: {"c":{"indoorUnit":{"status":{"mode":"heat"}}}}.
[12/11/2020, 2:15:09 PM] [Kumo] Heater/Cooler: set Active from 0 to 1
[12/11/2020, 2:15:10 PM] [Kumo] {
  r: { indoorUnit: { status: { mode: 'off' } } }
}
[12/11/2020, 2:15:10 PM] [Kumo] {
  r: { indoorUnit: { status: { mode: 'off' } } }
}
[12/11/2020, 2:15:17 PM] [Kumo] post_data: {"c":{"indoorUnit":{"status":{"mode":"heat"}}}}.
[12/11/2020, 2:15:17 PM] [Kumo] Heater/Cooler: set Active from 0 to 1
[12/11/2020, 2:15:18 PM] [Kumo] {
  r: { indoorUnit: { status: { mode: 'off' } } }
}
[12/11/2020, 2:15:18 PM] [Kumo] {
  r: { indoorUnit: { status: { mode: 'off' } } }
}
[12/11/2020, 2:15:22 PM] [Kumo] post_data: {"c":{"indoorUnit":{"status":{"mode":"heat"}}}}.
[12/11/2020, 2:15:22 PM] [Kumo] Heater/Cooler: set Active from 0 to 1
[12/11/2020, 2:15:22 PM] [Kumo] {
  r: { indoorUnit: { status: { mode: 'off' } } }
}
[12/11/2020, 2:15:22 PM] [Kumo] {
  r: { indoorUnit: { status: { mode: 'off' } } }
}

**Comment by derk1127** [comment] 2020-12-11 22:20
Here's what happen once I turn them off after:

}
[12/11/2020, 2:18:44 PM] [Kumo] queryDevice_Direct success.
[12/11/2020, 2:19:30 PM] [Kumo] post_data: {"c":{"indoorUnit":{"status":{"mode":"vent"}}}}.
[12/11/2020, 2:19:30 PM] [Kumo] Heater/Cooler: set Active from 1 to 0
[12/11/2020, 2:19:30 PM] [Kumo] {
  r: { indoorUnit: { status: { mode: 'heat' } } }
}
[12/11/2020, 2:19:30 PM] [Kumo] {
  r: { indoorUnit: { status: { mode: 'heat' } } }
}
[12/11/2020, 2:19:33 PM] [Kumo] post_data: {"c":{"indoorUnit":{"status":{"mode":"vent"}}}}.
[12/11/2020, 2:19:33 PM] [Kumo] Heater/Cooler: set Active from 1 to 0
[12/11/2020, 2:19:34 PM] [Kumo] {
  r: { indoorUnit: { status: { mode: 'heat' } } }
}
[12/11/2020, 2:19:34 PM] [Kumo] {
  r: { indoorUnit: { status: { mode: 'heat' } } }
}
[12/11/2020, 2:19:36 PM] [Kumo] post_data: {"c":{"indoorUnit":{"status":{"mode":"vent"}}}}.
[12/11/2020, 2:19:36 PM] [Kumo] Heater/Cooler: set Active from 1 to 0
[12/11/2020, 2:19:37 PM] [Kumo] {
  r: { indoorUnit: { status: { mode: 'heat' } } }
}
[12/11/2020, 2:19:37 PM] [Kumo] {
  r: { indoorUnit: { status: { mode: 'heat' } } }
}

**Comment by fjs21** [comment] 2020-12-18 19:14
Hmm. I mean it looks like it is posting the correcting command to either turn on heat mode or turn on vent mode. If you wait five minutes after sending the command, the device status does not change?

**Comment by derk1127** [comment] 2020-12-18 20:49
> Hmm. I mean it looks like it is posting the correcting command to either turn on heat mode or turn on vent mode. If you wait five minutes after sending the command, the device status does not change?

They still show as “no response” after five minutes.

**Comment by fjs21** [comment] 2020-12-18 20:51
Does the status of the device change in the Kumo app to reflect the command has been sent correctly? i.e. does the device turn on heat/vent.

**Comment by derk1127** [comment] 2020-12-18 21:20
> Does the status of the device change in the Kumo app to reflect the command has been sent correctly? i.e. does the device turn on heat/vent.

The unit turns on/off but I cannot control the fan speed when it shows “no response.”

**Comment by fjs21** [comment] 2020-12-18 21:24
Ok. It appears then that mode setting is working correctly and that matches the log.

As the fan speed is causing a problem, can you post the debug log when you change the speed of the fan?

**Comment by derk1127** [comment] 2020-12-18 21:37
I can't change the fan speed from Homekit when the device shows no response. The slider does not move. I did find this on my debug when I tried it once though. 

[12/18/2020, 1:27:39 PM] [Kumo] queryDevice_Direct success.
[12/18/2020, 1:27:39 PM] [Kumo] { _api_error: 'device_authentication_error' }
[12/18/2020, 1:27:39 PM] [Kumo] Kumo API: bad response from queryDevice_Direct - { _api_error: 'device_authentication_error' }
[12/18/2020, 1:27:39 PM] [Kumo] queryDevice_Direct failed.
[12/18/2020, 1:27:39 PM] [Kumo] Running interval
[12/18/2020, 1:27:39 PM] [Kumo] {

**Comment by bronze350** [comment] 2021-01-07 17:14
Still getting the device error with the newest plugin, when trying both the direct and unchecking the direct methods..  I have two outdoor systems, two branch boxes, and 10 indoor units of a few different models.. I am happy to help you test and improve the plugin, let me know how I can help. -Thanks.

**Comment by derk1127** [comment] 2021-01-08 08:56
I thought I was the only one. The frustrating thing is that because the fan controls go away when it’s non responsive, I can’t really log the error

**Comment by bronze350** [comment] 2021-01-08 13:37
Yes agreed. I think adding to the problem is the fact that the Kumocloud solution itself is slow to respond and buggy.. I removed the plug-in, I’ll wait to hear back as to if the developer needs help or not before I try again.

**Comment by PeterJ73** [comment] 2021-02-11 21:31
I've started seeing this error in my status using Kumo plugin 1.2.8. Also I do not see a notice to update to 1.3.8.

[2/10/2021, 10:07:53 PM] [Kumo] Kumo API: bad response from queryDevice_Direct - { _api_error: 'device_authentication_error' }
[2/10/2021, 10:07:53 PM] [Kumo] queryDevice_Direct failed.
[2/10/2021, 11:07:57 PM] [Kumo] queryDevice_Direct error: Time out on local IP connection..
[2/10/2021, 11:07:57 PM] [Kumo] queryDevice_Direct failed.
[2/10/2021, 11:12:33 PM] [Kumo] queryDevice_Direct error: Time out on local IP connection..
[2/10/2021, 11:12:33 PM] [Kumo] queryDevice_Direct failed.
[2/10/2021, 11:12:36 PM] [AugustLocks] [August Front Door] State was successfully set to lock
[2/10/2021, 11:12:46 PM] [Kumo] queryDevice_Direct error: FetchError: request to http://192.168.1.213/api?m=549907a7adeb381dc401177841dd70b745bb8fba76b91ef4cba292cb1df3906f failed, reason: connect EHOSTUNREACH 192.168.1.213:80
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-kumo/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH'
}.
[2/10/2021, 11:12:46 PM] [Kumo] queryDevice_Direct failed.
[2/10/2021, 11:13:00 PM] [Kumo] queryDevice_Direct error: FetchError: request to http://192.168.1.213/api?m=549907a7adeb381dc401177841dd70b745bb8fba76b91ef4cba292cb1df3906f failed, reason: connect EHOSTUNREACH 192.168.1.213:80
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-kumo/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH'
}.
[2/10/2021, 11:13:00 PM] [Kumo] queryDevice_Direct failed.
[2/11/2021, 1:07:57 AM] [Kumo] queryDevice_Direct error: Time out on local IP connection..
[2/11/2021, 1:07:57 AM] [Kumo] queryDevice_Direct failed.

**Comment by fjs21** [comment] 2021-02-13 20:29
> I can't change the fan speed from Homekit when the device shows no response. The slider does not move. I did find this on my debug when I tried it once though.
> 
> [12/18/2020, 1:27:39 PM] [Kumo] queryDevice_Direct success.
> [12/18/2020, 1:27:39 PM] [Kumo] { _api_error: 'device_authentication_error' }
> [12/18/2020, 1:27:39 PM] [Kumo] Kumo API: bad response from queryDevice_Direct - { _api_error: 'device_authentication_error' }
> [12/18/2020, 1:27:39 PM] [Kumo] queryDevice_Direct failed.
> [12/18/2020, 1:27:39 PM] [Kumo] Running interval
> [12/18/2020, 1:27:39 PM] [Kumo] {

Sorry for the delay. Life happens (three kids). I've not experienced this error yet with my unit and I'm not sure why it would crop up. Perhaps it has to do with the multiple units in your setup - could be something like too many requests causing the API to lock you request out.

@bronze350 - any help is always appreciated. I only have a single unit which works pretty robustly without these issues. It seems you have a pretty complex setup too. If we can get the problems nailed down to specifics then I'd be happy to work with you to fix them.

Also if any others have had this issue please post in this thread so we can get a better idea of how widespread this issue is? I'll see if I can get a poll of some sort posted.

**Comment by fjs21** [comment] 2021-02-13 20:43
@bronze350 - does the plugin correct enumerate all of your devices? can you post the debug log?

**Comment by derk1127** [comment] 2021-02-15 19:36
The new update may have fixed the “no response” but now I only have a dehumidifier switch and no fan speed slider.

**Comment by fjs21** [comment] 2021-02-15 21:50
Glad it solved the no response issue. The fan is now integrated into the heater/cooler device. Press and hold on the device and scroll and the fan is there. Slide over to the left to enable "auto" and then the speed is manually controlled by sliding to the right from quiet to the max speed.

**Comment by derk1127** [comment] 2021-02-16 06:07
Awesome thanks!!!

**Comment by fjs21** [comment] 2021-02-16 12:51
Great! I'm going to close this issue. Feel free to open it up if you have any more issues.

**Closed by fjs21** 2021-02-16 12:51 UTC
Labels: bug
